# Every Dockerfile starts with a base image
FROM ubuntu:22.04

# Run a command during image build
RUN echo "Hello form build time"

# Command that runs when container starts
CMD ["command-that-does-not-exist"]